In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings(action='ignore')
pd.set_option('display.max_columns',None)
#pd.set_option('display.max_rows',None)
pd.options.display.float_format="{:.5f}".format
plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

In [2]:
data = pd.read_csv('data/2023빅콘테스트_어드밴스드리그_예술의전당.csv')

# do : 국내 공연
kopis2018_do = pd.read_csv('data/DB검색_공연DB_201811_201910_국내.csv')
kopis2019_do = pd.read_csv('data/DB검색_공연DB_201911_202010_국내.csv')
kopis2020_do = pd.read_csv('data/DB검색_공연DB_202011_202110_국내.csv')
kopis2021_do = pd.read_csv('data/DB검색_공연DB_202111_202210_국내.csv')
kopis2022_do = pd.read_csv('data/DB검색_공연DB_202211_202307_국내.csv')

# kr : 내한 공연
kopis2018_kr = pd.read_csv('data/DB검색_공연DB_201811_201910_내한.csv')
kopis2019_kr = pd.read_csv('data/DB검색_공연DB_201911_202010_내한.csv')
kopis2020_kr = pd.read_csv('data/DB검색_공연DB_202011_202110_내한.csv')
kopis2021_kr = pd.read_csv('data/DB검색_공연DB_202111_202210_내한.csv')
kopis2022_kr = pd.read_csv('data/DB검색_공연DB_202211_202307_내한.csv')

In [3]:
data.head(1)

,age,gender,membership_type_1,membership_type_2,membership_type_3,membership_type_4,membership_type_5,membership_type_6,tran_date,tran_time,play_date,play_st_time,seat,price,ticket_cancel,discount_type,performance_code,pre_open_date,open_date,genre,place,running_time,intermission,member_yn
0,50.00000,F,골드,무료,그린,NaN,NaN,NaN,20220114,1512,20220204,2000,3층 BOX9 10,10000,2,일반,302,20220114.00000,20220115.00000,교향곡,콘서트홀,120,15,Y

In [4]:
data['seat'].value_counts().index

Index(['1층 9열 1', '1층 12열 18', '2층 BOX1 1', '1층 B블록 10열 1', '1층 9열 4',
       '1층 9열 2', '2층 BOX1 2', '1층 11열 17', '1층 9열 3', '1층 11열 5',
       ...
       '1층 C블록22열 3', '1층 C블록22열 4', '1층 C블록22열 8', '1층 C블록22열 5',
       '1층 C블록22열 7', '1층 C블록22열 6', '2층 A블록8열 12', '2층 E블록8열 13',
       '2층 A블록8열 13', '2층 E블록8열 12'],
      dtype='object', length=3525)

In [5]:
kopis2018_do.head(1)

,No.,공연명,장르,시작일,종료일,공연시설,공연장,객석수(석),제작,기획,주최,주관
0,1,제36회 대한민국국제음악제,서양음악(클래식),2019.10.24,2019.10.24,예술의전당,콘서트홀,"2,527",NaN,NaN,(사)한국음악협회,NaN

In [6]:
kopis_dos = [kopis2018_do, kopis2019_do, kopis2020_do, kopis2021_do, kopis2022_do]
kopis_do = pd.concat(kopis_dos, ignore_index=True)
kopis_do = kopis_do.iloc[:, 1:]

kopis_krs = [kopis2018_kr, kopis2019_kr, kopis2020_kr, kopis2021_kr, kopis2022_kr]
kopis_kr = pd.concat(kopis_krs, ignore_index=True)
kopis_kr = kopis_kr.iloc[:, 1:]

In [7]:
kopis_do = kopis_do.drop_duplicates()
kopis_kr = kopis_kr.drop_duplicates()

In [8]:
kopis_do.head(1)

,공연명,장르,시작일,종료일,공연시설,공연장,객석수(석),제작,기획,주최,주관
0,제36회 대한민국국제음악제,서양음악(클래식),2019.10.24,2019.10.24,예술의전당,콘서트홀,"2,527",NaN,NaN,(사)한국음악협회,NaN

In [9]:
kopis_kr.head(1)

,공연명,장르,시작일,종료일,공연시설,공연장,객석수(석),제작,기획,주최,주관
0,"서울국제음악제, 신포니에타 크라코비아: 오래된 이야기",서양음악(클래식),2019.10.27,2019.10.27,예술의전당,콘서트홀,"2,527",NaN,NaN,서울국제음악제,(주)오푸스(OPUS)

In [10]:
kopis_do['시작일'] = pd.to_datetime(kopis_do['시작일'], format='%Y.%m.%d')
kopis_do['시작일'] = kopis_do['시작일'].dt.strftime('%Y%m%d').astype(int)
kopis_do['종료일'] = pd.to_datetime(kopis_do['종료일'], format='%Y.%m.%d')
kopis_do['종료일'] = kopis_do['종료일'].dt.strftime('%Y%m%d').astype(int)

In [11]:
kopis_kr['시작일'] = pd.to_datetime(kopis_kr['시작일'], format='%Y.%m.%d')
kopis_kr['시작일'] = kopis_kr['시작일'].dt.strftime('%Y%m%d').astype(int)
kopis_kr['종료일'] = pd.to_datetime(kopis_kr['종료일'], format='%Y.%m.%d')
kopis_kr['종료일'] = kopis_kr['종료일'].dt.strftime('%Y%m%d').astype(int)

In [12]:
kopis_do['내한여부'] = 0
kopis_kr['내한여부'] = 1

In [13]:
kopis = pd.concat([kopis_do, kopis_kr], axis=0)
kopis = kopis.reset_index(drop=True)

In [14]:
kopis

,공연명,장르,시작일,종료일,공연시설,공연장,객석수(석),제작,기획,주최,주관,내한여부
0,제36회 대한민국국제음악제,서양음악(클래식),20191024,20191024,예술의전당,콘서트홀,"2,527",NaN,NaN,(사)한국음악협회,NaN,0
1,제179회 국립합창단 정기연주회,서양음악(클래식),20191017,20191017,예술의전당,콘서트홀,"2,527",NaN,NaN,(재)국립합창단,NaN,0
2,KBS교향악단과 김대진의 Mozart and Beethoven,서양음악(클래식),20191011,20191011,예술의전당,콘서트홀,"2,527",NaN,NaN,(재)KBS교향악단,(재)KBS교향악단,0
3,"서울국제음악제, 펜데레츠키 누가수난곡: 사람의 길을 묻다",서양음악(클래식),20191026,20191026,예술의전당,콘서트홀,"2,527",NaN,NaN,"서울국제음악제, (재)KBS교향악단",(주)오푸스(OPUS),0
4,제76회 서울오라토리오 정기연주회,서양음악(클래식),20191009,20191009,예술의전당,콘서트홀,"2,527",NaN,NaN,서울오라토리오,서울오라토리오,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1114,파리나무십자가 소년합창단 특별초청공연 [서울],서양음악(클래식),20221216,20221216,예술의전당,콘서트홀,"2,527",NaN,NaN,(주)에스피에이 엔터테인먼트(SPA Entertainment),NaN,1
1115,다니엘 바렌보임 & 베를린 슈타츠카펠레,서양음악(클래식),20221130,20221130,예술의전당,콘서트홀,"2,527",NaN,NaN,"SBS, (주)마스트미디어",(주)마스트미디어,1
1116,김선욱 & 유럽 챔버 오케스트라 (11.05),서양음악(클래식),20221105,20221105,예술의전당,콘서트홀,"2,527",(주)빈체로,NaN,(주)빈체로,NaN,1
1117,김선욱 & 유럽 챔버 오케스트라 (11.08),서양음악(클래식),20221108,20221108,예술의전당,콘서트홀,"2,527",NaN,NaN,(주)빈체로,NaN,1
1118,토마스 체헤트마이어 & 프랑스 오베르뉴 국립 오케스트라,서양음악(클래식),20221112,20221112,예술의전당,콘서트홀,"2,527",NaN,NaN,(주)더브릿지컴퍼니,(주)더브릿지컴퍼니,1

In [15]:
data_performance = data[['play_date','performance_code','genre','place']]

In [16]:
data_performance

         play_date  performance_code genre   place
0         20220204               302   교향곡    콘서트홀
1         20211009              1120    독주   리사이틀홀
2         20221105              2283    독주  IBK챔버홀
3         20190731              2798    독주   리사이틀홀
4         20220302               897    독주    콘서트홀
...            ...               ...   ...     ...
1920863   20190706              1265   실내악  IBK챔버홀
1920864   20230408               313   교향곡    콘서트홀
1920865   20210619               736    독주   리사이틀홀
1920866   20211127              1920    독주  IBK챔버홀
1920867   20210619              1995   실내악  IBK챔버홀

[1920868 rows x 4 columns]

In [17]:
data_concert = data_performance[data_performance['place']=='콘서트홀'].iloc[:,:3]

In [18]:
date_list = data_concert['play_date'].unique()

In [19]:
result = []
for i in date_list:
    x = len(data_concert[data_concert['play_date'] == i]['performance_code'].unique())
    if x == 1:
        result.append('True')
    else:
        result.append(i)

In [20]:
# 해당 날짜는 performance code가 2개 이상
for i in result:
    if i != 'True':
        print(i)

20230518
20210101
20210704

In [21]:
len(data_concert['performance_code'].unique())

703

In [22]:
data_concert = data_concert.drop_duplicates()
data_concert = data_concert.reset_index(drop=True)

In [23]:
data_concert

     play_date  performance_code genre
0     20220204               302   교향곡
1     20220302               897    독주
2     20190323               528   교향곡
3     20191109                44   교향곡
4     20190723               827   교향곡
..         ...               ...   ...
737   20191225              2932   클래식
738   20220407               166   교향곡
739   20210508               293   교향곡
740   20210914              2290    독주
741   20211212               494   교향곡

[742 rows x 3 columns]

In [24]:
# 예술의전당 + 콘서트홀
kopis['공연시설'] = kopis['공연시설'].replace({'예술의전당 ': '예술의전당'})
kopis_concert = kopis[(kopis['공연시설'] == '예술의전당') & (kopis['공연장'] == '콘서트홀')]
kopis_concert = kopis_concert.reset_index(drop=True)

In [25]:
kopis_concert

,공연명,장르,시작일,종료일,공연시설,공연장,객석수(석),제작,기획,주최,주관,내한여부
0,제36회 대한민국국제음악제,서양음악(클래식),20191024,20191024,예술의전당,콘서트홀,"2,527",NaN,NaN,(사)한국음악협회,NaN,0
1,제179회 국립합창단 정기연주회,서양음악(클래식),20191017,20191017,예술의전당,콘서트홀,"2,527",NaN,NaN,(재)국립합창단,NaN,0
2,KBS교향악단과 김대진의 Mozart and Beethoven,서양음악(클래식),20191011,20191011,예술의전당,콘서트홀,"2,527",NaN,NaN,(재)KBS교향악단,(재)KBS교향악단,0
3,"서울국제음악제, 펜데레츠키 누가수난곡: 사람의 길을 묻다",서양음악(클래식),20191026,20191026,예술의전당,콘서트홀,"2,527",NaN,NaN,"서울국제음악제, (재)KBS교향악단",(주)오푸스(OPUS),0
4,제76회 서울오라토리오 정기연주회,서양음악(클래식),20191009,20191009,예술의전당,콘서트홀,"2,527",NaN,NaN,서울오라토리오,서울오라토리오,0
...,...,...,...,...,...,...,...,...,...,...,...,...
943,파리나무십자가 소년합창단 특별초청공연 [서울],서양음악(클래식),20221216,20221216,예술의전당,콘서트홀,"2,527",NaN,NaN,(주)에스피에이 엔터테인먼트(SPA Entertainment),NaN,1
944,다니엘 바렌보임 & 베를린 슈타츠카펠레,서양음악(클래식),20221130,20221130,예술의전당,콘서트홀,"2,527",NaN,NaN,"SBS, (주)마스트미디어",(주)마스트미디어,1
945,김선욱 & 유럽 챔버 오케스트라 (11.05),서양음악(클래식),20221105,20221105,예술의전당,콘서트홀,"2,527",(주)빈체로,NaN,(주)빈체로,NaN,1
946,김선욱 & 유럽 챔버 오케스트라 (11.08),서양음악(클래식),20221108,20221108,예술의전당,콘서트홀,"2,527",NaN,NaN,(주)빈체로,NaN,1
947,토마스 체헤트마이어 & 프랑스 오베르뉴 국립 오케스트라,서양음악(클래식),20221112,20221112,예술의전당,콘서트홀,"2,527",NaN,NaN,(주)더브릿지컴퍼니,(주)더브릿지컴퍼니,1

In [26]:
kopis_concert = kopis_concert.drop_duplicates()
kopis_concert

,공연명,장르,시작일,종료일,공연시설,공연장,객석수(석),제작,기획,주최,주관,내한여부
0,제36회 대한민국국제음악제,서양음악(클래식),20191024,20191024,예술의전당,콘서트홀,"2,527",NaN,NaN,(사)한국음악협회,NaN,0
1,제179회 국립합창단 정기연주회,서양음악(클래식),20191017,20191017,예술의전당,콘서트홀,"2,527",NaN,NaN,(재)국립합창단,NaN,0
2,KBS교향악단과 김대진의 Mozart and Beethoven,서양음악(클래식),20191011,20191011,예술의전당,콘서트홀,"2,527",NaN,NaN,(재)KBS교향악단,(재)KBS교향악단,0
3,"서울국제음악제, 펜데레츠키 누가수난곡: 사람의 길을 묻다",서양음악(클래식),20191026,20191026,예술의전당,콘서트홀,"2,527",NaN,NaN,"서울국제음악제, (재)KBS교향악단",(주)오푸스(OPUS),0
4,제76회 서울오라토리오 정기연주회,서양음악(클래식),20191009,20191009,예술의전당,콘서트홀,"2,527",NaN,NaN,서울오라토리오,서울오라토리오,0
...,...,...,...,...,...,...,...,...,...,...,...,...
943,파리나무십자가 소년합창단 특별초청공연 [서울],서양음악(클래식),20221216,20221216,예술의전당,콘서트홀,"2,527",NaN,NaN,(주)에스피에이 엔터테인먼트(SPA Entertainment),NaN,1
944,다니엘 바렌보임 & 베를린 슈타츠카펠레,서양음악(클래식),20221130,20221130,예술의전당,콘서트홀,"2,527",NaN,NaN,"SBS, (주)마스트미디어",(주)마스트미디어,1
945,김선욱 & 유럽 챔버 오케스트라 (11.05),서양음악(클래식),20221105,20221105,예술의전당,콘서트홀,"2,527",(주)빈체로,NaN,(주)빈체로,NaN,1
946,김선욱 & 유럽 챔버 오케스트라 (11.08),서양음악(클래식),20221108,20221108,예술의전당,콘서트홀,"2,527",NaN,NaN,(주)빈체로,NaN,1
947,토마스 체헤트마이어 & 프랑스 오베르뉴 국립 오케스트라,서양음악(클래식),20221112,20221112,예술의전당,콘서트홀,"2,527",NaN,NaN,(주)더브릿지컴퍼니,(주)더브릿지컴퍼니,1

In [27]:
# 하루에 공연 2개 이상인 날들
value_counts = kopis_concert['시작일'].value_counts()

result = value_counts[value_counts >= 2]
print(sorted(result.index))

[20181108, 20190110, 20190214, 20190316, 20190411, 20190420, 20190815, 20190908, 20190919, 20191025, 20191221, 20201028, 20201029, 20201104, 20201225, 20210226, 20210408, 20210514, 20210515, 20210528, 20210529, 20210625, 20210627, 20210828, 20210829, 20210831, 20210908, 20210924, 20211022, 20211120, 20211126, 20211224, 20220128, 20220428, 20220505, 20220512, 20220527, 20220609, 20220714, 20220722, 20220826, 20220908, 20220923, 20221013, 20221015, 20221028, 20221125, 20221209, 20221223, 20230511]

In [28]:
# 시작일과 종료일이 동일하지 않은 공연들
result = []
for i in range(len(kopis_concert)):
    if kopis_concert.iloc[i,2] != kopis_concert.iloc[i,3]:
        result.append(i)

kopis_concert.iloc[result,:]

,공연명,장르,시작일,종료일,공연시설,공연장,객석수(석),제작,기획,주최,주관,내한여부
301,우리가곡 100년의 노래: 굿모닝 가곡,서양음악(클래식),20211008,20211010,예술의전당,콘서트홀,"2,527",NaN,NaN,예술의전당,NaN,0
319,손열음 피아노 리사이틀,서양음악(클래식),20210930,20211001,예술의전당,콘서트홀,"2,527",NaN,NaN,"예술의전당, (주)파이플랜즈 (pie plans), (주)크레디아뮤직앤아티스트",NaN,0
679,파란만장 100년의 드라마: 굿모닝 가곡 (앵콜),서양음악(클래식),20211201,20211202,예술의전당,콘서트홀,"2,527",NaN,NaN,예술의전당,NaN,0
710,조성진 피아노 리사이틀,서양음악(클래식),20230704,20230705,예술의전당,콘서트홀,"2,527",NaN,NaN,(주)크레디아뮤직앤아티스트,NaN,0

In [29]:
# 공연명을 저장할 빈 리스트 생성
matching_performance_names = []

# data_concert의 각 행에 대해 공연명 찾기
for index, row in data_concert.iterrows():
    play_date = row['play_date']
    matching_names = kopis_concert[(kopis_concert['시작일'] <= play_date) & (play_date <= kopis_concert['종료일'])]['공연명'].tolist()
    
    if matching_names:
        matching_performance_names.append(', '.join(matching_names))
    else:
        matching_performance_names.append(np.nan)

# 결과를 data_concert 데이터프레임에 추가
data_concert['공연명'] = matching_performance_names

# 결과 출력
data_concert

     play_date  performance_code genre                                    공연명
0     20220204               302   교향곡                                    NaN
1     20220302               897    독주       국립합창단 위대한 합창 Ⅰ, 칼 오르프 & 카르미나 부라나
2     20190323               528   교향곡                                오페라 카니발
3     20191109                44   교향곡                      러시아 명 피아노 협주곡 시리즈
4     20190723               827   교향곡             제17회 코리아니쉬 플루트 오케스트라 정기연주회
..         ...               ...   ...                                    ...
737   20191225              2932   클래식                                     선물
738   20220407               166   교향곡               한화와 함께하는 교향악축제, 대전시립교향악단
739   20210508               293   교향곡                        조수미 콘서트: 나의 어머니
740   20210914              2290    독주  클라라 주미 강 & 김선욱 베토벤 바이올린 소나타 전곡 (9.14)
741   20211212               494   교향곡                    미로슬라브 꿀띠쉐프 피아노 리사이틀

[742 rows x 4 columns]

In [30]:
data_concert.iloc[44, 3] = '구스타보 두다멜&LA필하모닉 오케스트라'
data_concert.iloc[45, 3] = '파리나무십자가소년합창단 특별 초청공연'
data_concert.iloc[102, 3] = '젊은 예술인 지원을 위한 예술기부 콘서트 II'
data_concert.iloc[106, 3] = '제63회 과천시립교향악단 정기연주회'
data_concert.iloc[137, 3] = '젊은 예술인 지원을 위한 예술기부 콘서트 IV'
data_concert.iloc[156, 3] = '한국을 이끄는 음악가 시리즈 4'
data_concert.iloc[241, 3] = '예술의전당 여름음악축제, 뷔에르 앙상블'
data_concert.iloc[244, 3] = '제783회 KBS교향악단 정기연주회 [서울]'
data_concert.iloc[252, 3] = '예술의전당 여름음악축제, SAC 페스티벌 오케스트라: 클로징 콘서트'
data_concert.iloc[264, 3] = '국립심포니오케스트라, DR’s Pick IV: 천지창조'

data_concert.iloc[314, 3] = '제767회 KBS교향악단 정기연주회'
data_concert.iloc[339, 3] = '한빛예술단의 Music in the Dark: Ballare'
data_concert.iloc[341, 3] = '트리니티필하모닉오케스트라 시그니쳐콘서트: 피아니스트 임동민 초청 차이콥스키의 열정'
data_concert.iloc[363, 3] = '미클로시 페레니 & 피닌 콜린스 듀오 콘서트 Ⅰ'
data_concert.iloc[372, 3] = '넥스트 스테이지'
data_concert.iloc[413, 3] = '오페라 옴니버스 & 팬텀'
data_concert.iloc[423, 3] = '제10회 사랑과 희망의 하모니'
data_concert.iloc[466, 3] = '어린이날100주년기념 소유진이 들려주는 음악이야기 (6시)'
data_concert.iloc[470, 3] = '조수미 & 프렌즈: In Love'
data_concert.iloc[495, 3] = '슈퍼노바 시리즈 I, 임지영x레미 제니에 듀오 리사이틀'

data_concert.iloc[505, 3] = '필하모니 코리아 창단연주회'
data_concert.iloc[531, 3] = '제763회 KBS교향악단 정기연주회'
data_concert.iloc[544, 3] = '미샤 마이스키 & 무직콜레기움 빈터투어'
data_concert.iloc[547, 3] = '서울시향 오스모 벤스케의 말러 교향곡 10번+'
data_concert.iloc[574, 3] = '제283회 부천필하모닉오케스트라 정기연주회'
data_concert.iloc[589, 3] = '예술의전당 여름음악축제, 앙상블블랭크 & 아르테늄 브라스밴드'
data_concert.iloc[592, 3] = '코리안심포니오케스트라, 환상적 무곡'
data_concert.iloc[638, 3] = '베토벤 황제와 영웅'
data_concert.iloc[651, 3] = '제766회 KBS교향악단 정기연주회'
data_concert.iloc[682, 3] = '사이먼 래틀 & 런던 심포니'

data_concert.iloc[699, 3] = '팬텀 스페셜 & 오케스트라 (5.14)'
data_concert.iloc[712, 3] = '제773회 KBS교향악단 정기연주회'
data_concert.iloc[731, 3] = 'The Class Concert with 임동혁'
data_concert.iloc[735, 3] = '스트라빈스키의 불새와 엘가의 첼로 협주곡'

In [31]:
data_concert = data_concert.dropna()
data_concert = data_concert.reset_index(drop=True)

In [32]:
merged_df = data_concert.merge(kopis_concert, left_on=['공연명', 'play_date'], right_on=['공연명', '시작일'], how='left')
merged_df = merged_df[['play_date','performance_code','genre','공연명','내한여부']]
merged_df = merged_df.fillna(0)
merged_df = merged_df.reset_index(drop=True)
merged_df = merged_df.drop_duplicates()
merged_df['내한여부'] = merged_df['내한여부'].astype(int)

In [33]:
merged_df

,play_date,performance_code,genre,공연명,내한여부
0,20220302,897,독주,"국립합창단 위대한 합창 Ⅰ, 칼 오르프 & 카르미나 부라나",0
1,20190323,528,교향곡,오페라 카니발,0
2,20191109,44,교향곡,러시아 명 피아노 협주곡 시리즈,1
3,20190723,827,교향곡,제17회 코리아니쉬 플루트 오케스트라 정기연주회,0
4,20190721,1528,클래식,"하루키, 라틴 지브리를 만나다",0
...,...,...,...,...,...
513,20191225,2932,클래식,선물,0
514,20220407,166,교향곡,"한화와 함께하는 교향악축제, 대전시립교향악단",0
515,20210508,293,교향곡,조수미 콘서트: 나의 어머니,0
516,20210914,2290,독주,클라라 주미 강 & 김선욱 베토벤 바이올린 소나타 전곡 (9.14),0
517,20211212,494,교향곡,미로슬라브 꿀띠쉐프 피아노 리사이틀,1

In [34]:
data_temp = data[data['place']=='콘서트홀']
data_temp = data_temp.reset_index(drop=True)
data_temp = data_temp.drop_duplicates()

In [35]:
result = data_temp.merge(merged_df, left_on=['play_date', 'performance_code','genre'], right_on=['play_date', 'performance_code','genre'], how='left')
result = result.dropna(subset=['공연명'])
result['내한여부'] = result['내한여부'].astype(int)
result

,age,gender,membership_type_1,membership_type_2,membership_type_3,membership_type_4,membership_type_5,membership_type_6,tran_date,tran_time,play_date,play_st_time,seat,price,ticket_cancel,discount_type,performance_code,pre_open_date,open_date,genre,place,running_time,intermission,member_yn,공연명,내한여부
1,50.00000,M,무료,NaN,NaN,NaN,NaN,NaN,20220206,1615,20220302,1930,1층 B블록12열 7,180000,0,일반,897,20220109.00000,20220110.00000,독주,콘서트홀,90,0,Y,"국립합창단 위대한 합창 Ⅰ, 칼 오르프 & 카르미나 부라나",0
2,30.00000,F,블루,무료,NaN,NaN,NaN,NaN,20181124,1145,20190323,2000,1층 A블록2열 1,144000,2,블루회원 할인20%,528,20181119.00000,20181119.00000,교향곡,콘서트홀,100,15,Y,오페라 카니발,0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20191020,1459,20191109,1700,3층 E블록4열 8,0,0,초대권,44,NaN,20191023.00000,교향곡,콘서트홀,100,15,N,러시아 명 피아노 협주곡 시리즈,1
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190613,954,20190723,2000,2층 D블록8열 4,0,0,초대권,827,20190602.00000,20190602.00000,교향곡,콘서트홀,120,20,N,제17회 코리아니쉬 플루트 오케스트라 정기연주회,0
5,NaN,F,블루,무료,NaN,NaN,NaN,NaN,20190703,908,20190721,1700,1층 C블록17열 3,75000,0,일반,1528,NaN,20190413.00000,클래식,콘서트홀,100,15,N,"하루키, 라틴 지브리를 만나다",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1096948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20190503,1659,20190523,1930,합창석 G블록4열 19,0,0,초대권,2253,20190519.00000,20190519.00000,클래식,콘서트홀,120,15,N,제213회 코리안심포니오케스트라 정기연주회,0
1096949,60.00000,F,무료,그린,NaN,NaN,NaN,NaN,20210618,1509,20210704,1500,1층 A블록2열 2,90000,2,일반,887,20210618.00000,20210620.00000,교향곡,콘서트홀,110,20,Y,에델 라인클랑 단독 콘서트: Overture,0
1096950,50.00000,M,무료,NaN,NaN,NaN,NaN,NaN,20230522,1729,20230613,1700,3층 A블록6열 4,10000,0,일반,2825,20230505.00000,20230507.00000,교향곡,콘서트홀,120,15,Y,"한화와 함께하는 교향악축제, 성남시립교향악단 (6.13)",0
1096952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20200726,1655,20200818,1930,1층 D블록20열 8,0,0,기획사판매,850,20200719.00000,20200720.00000,합창,콘서트홀,110,15,N,오케스트라 앙상블 서울 OES의 베토벤 시리즈 IV,0
1096953,20.00000,F,무료,싹틔우미,NaN,NaN,NaN,NaN,20221224,1223,20230408,1700,3층 B블록5열 4,21000,0,청소년(만7세~만24세/본인만)30%,313,NaN,20221223.00000,교향곡,콘서트홀,120,0,Y,한국예술종합학교 개교 30주년 기념 음악회: 새로운 비상(飛上),0

In [36]:
result.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 791458 entries, 1 to 1096953
Data columns (total 26 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   age                350895 non-null  float64
 1   gender             351105 non-null  object
 2   membership_type_1  351105 non-null  object
 3   membership_type_2  284185 non-null  object
 4   membership_type_3  102989 non-null  object
 5   membership_type_4  18570 non-null   object
 6   membership_type_5  856 non-null     object
 7   membership_type_6  0 non-null       float64
 8   tran_date          791458 non-null  int64
 9   tran_time          791458 non-null  int64
 10  play_date          791458 non-null  int64
 11  play_st_time       791458 non-null  int64
 12  seat               791458 non-null  object
 13  price              791458 non-null  int64
 14  ticket_cancel      791458 non-null  int64
 15  discount_type      791458 non-null  object
 16  performance_code   791458 non-null  int64
 17  pre_open_date      516992 non-null  float64
 18  open_date          791458 non-null  float64
 19  genre              791458 non-null  object
 20  place              791458 non-null  object
 21  running_time       791458 non-null  int64
 22  intermission       791458 non-null  int64
 23  member_yn          791458 non-null  object
 24  공연명                791458 non-null  object
 25  내한여부               791458 non-null  int32
dtypes: float64(4), int32(1), int64(9), object(12)
memory usage: 160.0+ MB

In [37]:
result.to_csv('data/제공데이터_공연명_내한_매칭.csv', index=False, encoding='utf-8')